// Generated by CoffeeScript 1.4.0
(function() {
  var changeElement, changeFont, test;

  chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
    var element;
    return element = request.element;
  });

  test = function() {
    return alert("test");
  };

  changeFont = function(font, element) {
    return chrome.tabs.getSelected(null, function(tab) {
      return chrome.tabs.sendMessage(tab.id, {
        action: "changeFont",
        font: font,
        element: element
      });
    });
  };

  changeElement = function(element, changeClass) {
    alert('changing element');
    return chrome.tabs.getSelected(null, function(tab) {
      return chrome.tabs.sendMessage(tab.id, {
        action: "changeElement",
        element: element,
        changeClass: changeClass
      });
    });
  };

}).call(this);
