// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
      var element, font;
      if (request.action === "changeElement") {
        $(request.element).wrap('<div class=' + '"' + request.changeClass + '"' + ' />');
      }
      if (request.action === "changeFont") {
        font = request.font;
        element = request.element;
        $("head").append("<link href='http://fonts.googleapis.com/css?family=" + font + "' rel='stylesheet' type='text/css'>");
        font = font.split("+").join(" ");
        $(request.element).css;
        return $(element).css('font-family', font);
      }
    });
    $('h1').click(function(e) {
      return chrome.extension.sendMessage({
        "element": "h1"
      });
    });
    $('h2').click(function(e) {
      return chrome.extension.sendMessage({
        "element": "h2"
      });
    });
    $('h3').click(function(e) {
      return chrome.extension.sendMessage({
        "element": "h3"
      });
    });
    return $('p').click(function(e) {
      return chrome.extension.sendMessage({
        "element": "p"
      });
    });
  });

}).call(this);
