// Generated by CoffeeScript 1.4.0
(function() {
  var changeFont;

  $(document).ready(function() {
    $('body').append('\
      <!-- Modal -->\
      <div id="fontModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">\
        <div class="modal-header">\
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>\
          <h3 id="myModalLabel">Change font</h3>\
        </div>\
        <div class="modal-body">\
          <select name="font-list" id="font-list">\
            <option value="Raleway">Raleway</option>\
            <option value="Gabriela"> Gabriela </option>\
            <option value="Abril+Fatface">Abril Fatface</option>\
            <option value="Gentium+Book+Basic">Gentium Book Basic</option>\
            <option value="Gravitas+One">Gravitas One</option>\
            <option value="Lato">Lato</option>\
            <option value="Merriweather">Merriweather</option>\
            <option value="Old+Standard+TT">Old Standard TT</option>\
            <option value="Open+Sans">Open Sans</option>\
            <option value="Playfair+Display">Playfair Display</option>\
            <option value="PT+Sans">PT Sans</option>\
            <option value="PT+Sans+Narrow">PT Sans Narrow</option>\
            <option value="PT+Serif">PT Serif</option>\
            <option value="Vollkorn">Vollkorn</option>\
          </select>\
        <textarea name="Tony" id="changeFontSize" cols="1" rows="1">Current font size:</textarea>\
        <input id="fontColor" class="color" value="000000" >\
        </div>\
        <div class="modal-footer">\
          <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>\
          <button id="fontChange" class="btn btn-primary">Save changes</button>\
        </div>\
      </div>  \
    ');
    $(document).bind('keypress', function(e) {
      var changeClass, currFontSize, tagName;
      if (event.shiftKey && event.which === 74) {
        currFontSize = $('.clicked').css('font-size');
        $("#changeFontSize").val(currFontSize);
        $("#fontModal").modal();
      }
      if (event.shiftKey && event.which === 87) {
        changeClass = window.prompt("What class to wrap with");
        if (changeClass != null) {
          $('.clicked').wrap('<div class=' + "'" + changeClass + "'" + '/>');
        }
      }
      if (event.shiftKey && event.which === 84) {
        tagName = window.prompt("tagName?", "" + ($('.clicked').prop('tagName').toLowerCase()));
        if (tagName != null) {
          $('.clicked').replaceWith(function() {
            return $("<" + tagName + " />").append($('.clicked').contents());
          });
        }
      }
      if (event.shiftKey && event.which === 68) {
        return $('.clicked').draggable({
          grid: [50, 50],
          disabled: false,
          stop: function() {
            return $(this).draggable('disable');
          }
        });
      }
    });
    chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
      var changeClass, changeTag, element, text;
      if (request.action === "loadBootstrap") {
        $("head").append("          <link href='//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css' rel='stylesheet'>        ");
        $('body').wrap('<div class="container" />');
      }
      if (request.action === "changeElement") {
        element = $('.clicked');
        changeClass = request.changeClass;
        if (changeClass === "navbar") {
          element.wrap('<div class="navbar" />');
          element.addClass('brand');
          element.wrap('<div class="navbar-inner" />');
          $(".navbar-inner").append('<ul class="nav pull-right sortable"></ul>');
        } else if (changeClass === "nav") {
          text = element.text();
          element.remove();
          $('ul.nav').append("<li><a href='#'>" + text + "</a></li>");
        } else if (changeClass === "addToHero") {
          $(".hero-unit").append(element);
        } else {
          element.wrap('<div class=' + '"' + changeClass + '"' + ' />');
        }
      }
      if (request.action === "changeTagName") {
        changeTag = request.changeTag;
        element = $('.clicked');
        element.replaceWith(function() {
          return $("<h2 />").append(element.contents());
        });
      }
      if (request.action === "changeFont") {
        return changeFont(request.font, request.fontSize, request.color);
      }
    });
    $('body').on('click', "#fontChange", function(e) {
      var color, font, fontSize;
      font = $('#font-list').val();
      fontSize = $("#changeFontSize").val();
      color = $("#fontColor").val();
      return changeFont(font, fontSize, color);
    });
    return $('body').on("click", "h1, h2, h3, p, a, li", function(e) {
      var x;
      e.preventDefault();
      x = $(this);
      $('.clicked').css('background', 'none');
      $('.clicked').removeClass('clicked');
      x.addClass('clicked');
      x.css('background', 'rgb(255, 251, 204)');
      return chrome.extension.sendMessage({
        "tagName": x.prop("tagName").toLowerCase(),
        "fontSize": x.css("font-size")
      });
    });
  });

  changeFont = function(font, fontSize, color) {
    var element;
    font = font;
    element = $('.clicked');
    fontSize = fontSize;
    color = "#" + color;
    $("head").append("    <link href='http://fonts.googleapis.com/css?family=" + font + "' rel='stylesheet' type='text/css'>    ");
    font = font.split("+").join(" ");
    element.css('font-family', font);
    element.css('font-size', fontSize);
    return element.css('color', color);
  };

}).call(this);
