// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var bkg;
    $('#loadBootstrap').click(function(e) {
      e.preventDefault();
      return bkg.loadBootstrap();
    });
    bkg = chrome.extension.getBackgroundPage();
    $('#getPageElement').click(function(e) {
      var popupVars;
      popupVars = bkg.getpopupVars();
      if (popupVars.tagName != null) {
        $("#elementSelectedText").val(popupVars.tagName);
        return $("#changeFontSize").val(popupVars.fontSize);
      } else {
        $("#elementSelectedText").val("h1");
        return $("#changeFontSize").val("15px");
      }
    });
    $('#changeElement').click(function(e) {
      var changeClass, element;
      e.preventDefault();
      element = $("#elementSelectedText").val();
      changeClass = $("#class-list").val();
      return bkg.changeElement(element, changeClass);
    });
    return $('#font-style').click(function(e) {
      var color, element, font, fontSize;
      e.preventDefault();
      font = $('#font-list').val();
      element = $("#elementSelectedText").val();
      fontSize = $("#changeFontSize").val();
      color = $("#fontColor").val();
      return bkg.changeFont(element, font, fontSize, color);
    });
  });

}).call(this);
